### ISSUE TITLE
Repo bei travis-ci eintragen

### ISSUE THREAD

**Issue by jojahner** [codepreller/eve-participation-system#10]
Ein CI-Server in der Cloud. Der fuehrt immer schoen unsere specs aus.

Das muss aber @codepreller machen, da er der owner des repo ist

**Comment by codepreller** [comment]
travis ist eingerichtet. commit der initialen .travis.yml: 91768237cedfca00467e6a112816372434cbec22

https://travis-ci.org/codepreller/eve-participation-system
