### ISSUE TITLE
fleet duration input hh:mm

### ISSUE THREAD

**Issue by Isoterik** [codepreller/eve-participation-system#9]
make the fleet duration input only available in hh:mm for better statistical processing.

**Comment by Isoterik** [comment]
forgotten to mention releated commits:
https://github.com/codepreller/eve-participation-system/commit/a7b725f40fec3f65f4dfdb01fc8828283b95f331
https://github.com/codepreller/eve-participation-system/commit/084178ead82344edbe6f2aca53ebfeaa8abb6139

**Comment by codepreller** [comment]
after discussion:
- switching hours and minutes dropdowns to start and end datetime field tag
- adding started_at and ended_at to the db
